[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/create-checkout"
  status = 200

[[redirects]]
  from = "/api/webhooks/stripe"
  to = "/.netlify/functions/stripe-webhook"
  status = 200

[[redirects]]
  from = "/pages/product-standard.html"
  to = "/pages/product.html"
  status = 301

[[redirects]]
  from = "/pages/product-panorama.html"
  to = "/pages/product.html"
  status = 301

[[redirects]]
  from = "/pages/product-aerial.html"
  to = "/pages/product.html"
  status = 301
